version: '3.3'

services:
  base-lib:
    image: ${REGISTRY}/${NAMESPACE}/${BASE_IMAGE_NAME}:v1
    volumes:
      - python-libs:/usr/local/lib/python3.9/site-packages
    command: >
      bash -c "
        cp -r /usr/local/lib/python3.9/site-packages.bak/* /usr/local/lib/python3.9/site-packages/ || true;
        sleep infinity"
    healthcheck:
      test: ["CMD", "test", "-d", "/usr/local/lib/python3.9/site-packages/torch"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    environment:
      - COMPOSE_HTTP_TIMEOUT=200

  app:
    image: ${REGISTRY}/${NAMESPACE}/${APP_IMAGE_NAME}:${GITHUB_SHA:-latest}
    ports:
      - "8000:8000"
    volumes:
      - python-libs:/opt/base-packages:ro
    environment:
      - PYTHONPATH=/usr/local/lib/python3.9/site-packages:/opt/base-packages
      - COMPOSE_HTTP_TIMEOUT=200
    depends_on:
      - base-lib

volumes:
  python-libs: 